function y = mLowpass(x, Fc, Fs)

Ap = 0.01;
Ast = 60;
N = 200;

if (Fc < 3250)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',3000,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
elseif (Fc >= 3250 && Fc < 3750)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',3500,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
elseif (Fc >= 3750 && Fc < 4250)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',4000,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
elseif (Fc >= 4250 && Fc < 4750)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',4500,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
elseif (Fc >= 4750 && Fc < 5250)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',5000,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
elseif (Fc >= 5250 && Fc < 5750)
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',5500,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
else
    LPF = dsp.LowpassFilter(...
        'DesignForMinimumOrder',false,...
        'SampleRate',Fs,...
        'PassbandFrequency',6000,...
        'FilterOrder',N,...
        'PassbandRipple',Ap,...
        'StopbandAttenuation',Ast);
    x_filtered = LPF(x);
    delay = N/2;
    N = length(x);
    y = zeros(N,1);
    y(1:N-delay) = x_filtered(delay+1:end);
    y(N-delay+1:end) = x_filtered(1:delay);
end

end

